import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml",
  "~/.config/alacritty/keybindings.toml"
]

[window]

decorations = "None"
dimensions = { columns = 60, lines = 20 }
padding = { x = 15, y = 15 }

[font]

size = 21

normal = { family = "AnonymicePro Nerd Font", style = "Regular" }
bold = { family = "AnonymicePro Nerd Font", style = "Regular" }
italic = { family = "AnonymicePro Nerd Font", style = "Regular" }
bold_italic = { family = "AnonymicePro Nerd Font", style = "Regular" }

